---
- name: install redhat dependencies
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - cyrus-sasl-plain
    - ca-certificates
    - mailx

- name: remove redhat old exim4
  yum:
    name: '{{ item }}'
    state: absent
  with_items:
    - exim

- name: install postfix
  yum:
    name: postfix
    state: "{{ postfix_state|default('present') }}"
