---
- include: install_debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - smtp
    - postfix

- include: install_redhat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - smtp
    - postfix

- include: configure.yml
  tags:
    - smtp
    - postfix
